-- Chạy đoạn mã SQL này trong SQL Editor của Supabase để tạo bảng lưu trữ dữ liệu

-- Xóa bảng cũ nếu đã tạo (đề phòng trường hợp đã tạo bị lỗi)
DROP TABLE IF EXISTS submissions;

CREATE TABLE submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  dms_code TEXT,
  employee_id TEXT,
  gpkd_license_num TEXT,
  gpkd_business_name TEXT,
  cccd_id_num TEXT,
  cccd_full_name TEXT,
  raw_ocr_gpkd TEXT,
  raw_ocr_cccd TEXT,
  gpkd_image_url TEXT,
  cccd_image_url TEXT
);

-- Tắt Row Level Security (RLS) để cho phép mọi thao tác đọc/ghi tự do đối với bảng 'submissions'
ALTER TABLE submissions DISABLE ROW LEVEL SECURITY;

---------------------------------------------------------------------------
-- HƯỚNG DẪN TẠO BẢNG LƯU TRỮ CÁC MÃ DMS HỢP LỆ (Dành cho tính năng Import Excel)
---------------------------------------------------------------------------
-- Chạy đoạn mã sau để tạo bảng valid_dms lưu trữ các mã DMS được import tử Excel
DROP TABLE IF EXISTS valid_dms CASCADE;
CREATE TABLE valid_dms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  code TEXT UNIQUE NOT NULL
);

ALTER TABLE valid_dms DISABLE ROW LEVEL SECURITY;

---------------------------------------------------------------------------
-- HƯỚNG DẪN TẠO STORAGE CHO ẢNH (BẮT BUỘC)
---------------------------------------------------------------------------
-- Chạy câu lệnh SQL sau để tạo bucket tên là 'images' (Storage):
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true) ON CONFLICT DO NOTHING;

-- Tắt RLS (cho phép upload ảnh thoải mái đối với file upload server-side) cho Storage:
CREATE POLICY "Allow All operations"
ON storage.objects FOR ALL USING (bucket_id = 'images');